trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  python_version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python_version)'
    architecture: 'x64'

- script: |
    pip install Django==4.2
    pip install django-environ
    pip install virtualenv
    source antenv/bin/activate
    virtualenv antenv
    python -m pip install --upgrade pip setuptools wheel
    pip install --user django-crispy-forms
    pip install celery
    pip install django_celery_results
    pip install Pillow
    sudo apt-get install python3-dev libxml2-dev libxslt1-dev zlib1g-dev libsasl2-dev libldap2-dev build-essential libssl-dev libffi-dev libmysqlclient-dev libjpeg-dev libpq-dev libjpeg8-dev liblcms2-dev libblas-dev libatlas-base-dev
    pip install git+https://github.com/azure-samples/ms-identity-python-utilities@main
    sudo pip install python-ldap
    apt-get install tk
    python -m pip install cx_Oracle --upgrade
    pip install unittest-xml-reporting
    pip install -r requirements.txt
  displayName: 'Install prerequisites'
  
- script: |
    zip -r artifact.zip . -x ".*" -x "test*" -x "newenv/*" -x "azure-pipelines.yml"
  displayName: Create a .ZIP file artifact

- task: PublishBuildArtifacts@1
  displayName: Publish build artifact
  inputs:
    pathToPublish: './artifact.zip'
    artifactName: artifact