# Generated by Django 4.0.5 on 2023-08-10 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='approvers',
            field=models.ManyToManyField(blank=True, null=True, related_name='document_approvers', to=settings.AUTH_USER_MODEL),
        ),
    ]
