# Generated by Django 4.0.5 on 2023-08-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_approvers'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='a_signatory_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='b_signatory_signed',
            field=models.BooleanField(default=False),
        ),
    ]
