# Generated by Django 4.0.5 on 2023-08-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_a_signatory_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='document_categories/%Y/%m/%d/'),
        ),
    ]
