# Generated by Django 4.0.5 on 2023-08-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_category_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='file',
            field=models.FileField(default=0, upload_to='document_categories/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
