# Generated by Django 4.0.5 on 2023-08-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_category_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
