# Generated by Django 4.0.5 on 2023-08-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_completed_document_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
